"""Static data for Verb Practice: verb lists, meanings and constants.

Pure data — no I/O, no heavy imports.  File locations live in verbs.paths.
"""
# ── Verb lists ────────────────────────────────────────────────────────────────
verbos_irregulares = [
    ["ser/estar","be","was-were","been"],["tener","have","had","had"],
    ["hacer","do","did","done"],["decir","say","said","said"],
    ["ir","go","went","gone"],["obtener","get","got","gotten"],
    ["hacer/crear","make","made","made"],["saber/conocer","know","knew","known"],
    ["pensar","think","thought","thought"],["tomar","take","took","taken"],
    ["ver","see","saw","seen"],["venir","come","came","come"],
    ["dar","give","gave","given"],["encontrar","find","found","found"],
    ["decir/contar","tell","told","told"],["convertirse","become","became","become"],
    ["mostrar","show","showed","shown"],["dejar/irse","leave","left","left"],
    ["sentir","feel","felt","felt"],["poner","put","put","put"],

    ["traer","bring","brought","brought"],["empezar","begin","began","begun"],
    ["mantener","keep","kept","kept"],["sostener","hold","held","held"],
    ["oír","hear","heard","heard"],["permitir","let","let","let"],
    ["significar","mean","meant","meant"],["establecer","set","set","set"],
    ["conocer/reunirse","meet","met","met"],["correr","run","ran","run"],
    ["pagar","pay","paid","paid"],["sentarse","sit","sat","sat"],
    ["hablar","speak","spoke","spoken"],["acostarse","lie","lay","lain"],
    ["liderar","lead","led","led"],["leer","read","read","read"],
    ["crecer","grow","grew","grown"],["perder","lose","lost","lost"],
    ["enviar","send","sent","sent"],["volar","fly","flew","flown"],

    ["vestir","wear","wore","worn"],["escribir","write","wrote","written"],
    ["beber","drink","drank","drunk"],["estar de pie","stand","stood","stood"],
    ["nadar","swim","swam","swum"],["cantar","sing","sang","sung"],
    ["gastar","spend","spent","spent"],["congelar","freeze","froze","frozen"],
    ["elevarse","rise","rose","risen"],["conducir","drive","drove","driven"],
    ["cortar","cut","cut","cut"],["caer","fall","fell","fallen"],
    ["construir","build","built","built"],["dibujar","draw","drew","drawn"],
    ["comprar","buy","bought","bought"],["entender","understand","understood","understood"],
    ["elegir","choose","chose","chosen"],["comer","eat","ate","eaten"],
    ["olvidar","forget","forgot","forgotten"],["romper","break","broke","broken"],

    ["robar","steal","stole","stolen"],["enseñar","teach","taught","taught"],
    ["lanzar","throw","threw","thrown"],["despertar","wake","woke","woken"],
    ["ganar","win","won","won"],["alimentar","feed","fed","fed"],
    ["atrapar","catch","caught","caught"],["soñar","dream","dreamt","dreamt"],
    ["quemar","burn","burnt","burnt"],["aprender","learn","learnt","learnt"],
    ["oler","smell","smelt","smelt"],["prestar","lend","lent","lent"],
    ["apostar","bet","bet","bet"],["costar","cost","cost","cost"],
    ["golpear fuerte","hit","hit","hit"],["herir","hurt","hurt","hurt"],
    ["cerrar","shut","shut","shut"],["extender","spread","spread","spread"],
    ["dividir","split","split","split"],["pelear","fight","fought","fought"],
]
verbos_regulares = [
    # Bloque 1 - Esenciales cotidianos
    ["querer","want","wanted"],["necesitar","need","needed"],
    ["gustar","like","liked"],["encantar","love","loved"],
    ["odiar","hate","hated"],["usar","use","used"],
    ["trabajar","work","worked"],["llamar","call","called"],
    ["preguntar","ask","asked"],["ayudar","help","helped"],
    ["intentar","try","tried"],["mirar","look","looked"],
    ["ver (mirar algo)","watch","watched"],["escuchar","listen","listened"],
    ["jugar","play","played"],["empezar","start","started"],
    ["parar","stop","stopped"],["terminar","finish","finished"],
    ["darse cuenta","realize","realized"],["vivir","live","lived"],

    # Bloque 2 - Acciones frecuentes
    ["quedarse","stay","stayed"],["hablar","talk","talked"],
    ["abrir","open","opened"],["cerrar","close","closed"],
    ["esperar","wait","waited"],["recordar","remember","remembered"],
    ["buscar","search","searched"],["cambiar","change","changed"],
    ["cocinar","cook","cooked"],["viajar","travel","traveled"],
    ["llegar","arrive","arrived"],["estar de acuerdo","agree","agreed"],
    ["explicar","explain","explained"],["creer","believe","believed"],
    ["mover","move","moved"],["imaginar","imagine","imagined"],
    ["decidir","decide","decided"],["disfrutar","enjoy","enjoyed"],
    ["evitar","avoid","avoided"],["practicar","practice","practiced"],

    # Bloque 3 - Acciones de organización y vida diaria
    ["planear","plan","planned"],["aceptar","accept","accepted"],
    ["recibir","receive","received"],["escribir mensaje","text","texted"],
    ["arreglar","fix","fixed"],["cancelar","cancel","canceled"],
    ["pasar","pass","passed"],["fallar","fail","failed"],
    ["tener éxito","succeed","succeeded"],["gestionar","manage","managed"],
    ["unirse","join","joined"],["apoyar","support","supported"],
    ["llevar","carry","carried"],["preparar","prepare","prepared"],
    ["incluir","include","included"],["guardar","save","saved"],
    ["lavar","wash","washed"],["revisar","review","reviewed"],
    ["verificar","check","checked"],["proteger","protect","protected"],

    # Bloque 4 - Acciones técnicas y comunicación
    ["cubrir","cover","covered"],["reducir","reduce","reduced"],
    ["aumentar","increase","increased"],["grabar","record","recorded"],
    ["anotar","note","noted"],["comparar","compare","compared"],
    ["diseñar","design","designed"],["comunicar","communicate","communicated"],
    ["organizar","organize","organized"],["describir","describe","described"],
    ["discutir","discuss","discussed"],["mencionar","mention","mentioned"],
    ["notar","notice","noticed"],["sugerir","suggest","suggested"],
    ["adivinar","guess","guessed"],["ordenar/pedir","order","ordered"],
    ["recordar a alguien","remind","reminded"],["responder","answer","answered"],
    ["preferir","prefer","preferred"],["visitar","visit","visited"],
]

# Spanish conjugations per verb: base form -> (pretérito, participio).
# Used to reveal the meaning of the exact form you typed:
#   eat -> comer,  ate -> comí,  eaten -> comido
SPANISH_FORMS = {
    # irregular
    "be":("fui/estuve","sido/estado"), "have":("tuve","tenido"),
    "do":("hice","hecho"), "say":("dije","dicho"),
    "go":("fui","ido"), "get":("obtuve","obtenido"),
    "make":("hice/creé","hecho/creado"), "know":("supe/conocí","sabido/conocido"),
    "think":("pensé","pensado"), "take":("tomé","tomado"),
    "see":("vi","visto"), "come":("vine","venido"),
    "give":("di","dado"), "find":("encontré","encontrado"),
    "tell":("dije/conté","dicho/contado"), "become":("me convertí","convertido"),
    "show":("mostré","mostrado"), "leave":("dejé/me fui","dejado/ido"),
    "feel":("sentí","sentido"), "put":("puse","puesto"),
    "bring":("traje","traído"), "begin":("empecé","empezado"),
    "keep":("mantuve","mantenido"), "hold":("sostuve","sostenido"),
    "hear":("oí","oído"), "let":("permití","permitido"),
    "mean":("significó","significado"), "set":("establecí","establecido"),
    "meet":("conocí/me reuní","conocido/reunido"), "run":("corrí","corrido"),
    "pay":("pagué","pagado"), "sit":("me senté","sentado"),
    "speak":("hablé","hablado"), "lie":("me acosté","acostado"),
    "lead":("lideré","liderado"), "read":("leí","leído"),
    "grow":("crecí","crecido"), "lose":("perdí","perdido"),
    "send":("envié","enviado"), "fly":("volé","volado"),
    "wear":("vestí","vestido"), "write":("escribí","escrito"),
    "drink":("bebí","bebido"), "stand":("estuve de pie","estado de pie"),
    "swim":("nadé","nadado"), "sing":("canté","cantado"),
    "spend":("gasté","gastado"), "freeze":("congelé","congelado"),
    "rise":("me elevé","elevado"), "drive":("conduje","conducido"),
    "cut":("corté","cortado"), "fall":("caí","caído"),
    "build":("construí","construido"), "draw":("dibujé","dibujado"),
    "buy":("compré","comprado"), "understand":("entendí","entendido"),
    "choose":("elegí","elegido"), "eat":("comí","comido"),
    "forget":("olvidé","olvidado"), "break":("rompí","roto"),
    "steal":("robé","robado"), "teach":("enseñé","enseñado"),
    "throw":("lancé","lanzado"), "wake":("desperté","despertado"),
    "win":("gané","ganado"), "feed":("alimenté","alimentado"),
    "catch":("atrapé","atrapado"), "dream":("soñé","soñado"),
    "burn":("quemé","quemado"), "learn":("aprendí","aprendido"),
    "smell":("olí","olido"), "lend":("presté","prestado"),
    "bet":("aposté","apostado"), "cost":("costó","costado"),
    "hit":("golpeé fuerte","golpeado fuerte"), "hurt":("herí","herido"),
    "shut":("cerré","cerrado"), "spread":("extendí","extendido"),
    "split":("dividí","dividido"), "fight":("peleé","peleado"),
    # regular
    "want":("quise","querido"), "need":("necesité","necesitado"),
    "like":("me gustó","gustado"), "love":("me encantó","encantado"),
    "hate":("odié","odiado"), "use":("usé","usado"),
    "work":("trabajé","trabajado"), "call":("llamé","llamado"),
    "ask":("pregunté","preguntado"), "help":("ayudé","ayudado"),
    "try":("intenté","intentado"), "look":("miré","mirado"),
    "watch":("vi","visto"), "listen":("escuché","escuchado"),
    "play":("jugué","jugado"), "start":("empecé","empezado"),
    "stop":("paré","parado"), "finish":("terminé","terminado"),
    "realize":("me di cuenta","dado cuenta"), "live":("viví","vivido"),
    "stay":("me quedé","quedado"), "talk":("hablé","hablado"),
    "open":("abrí","abierto"), "close":("cerré","cerrado"),
    "wait":("esperé","esperado"), "remember":("recordé","recordado"),
    "search":("busqué","buscado"), "change":("cambié","cambiado"),
    "cook":("cociné","cocinado"), "travel":("viajé","viajado"),
    "arrive":("llegué","llegado"), "agree":("estuve de acuerdo","estado de acuerdo"),
    "explain":("expliqué","explicado"), "believe":("creí","creído"),
    "move":("moví","movido"), "imagine":("imaginé","imaginado"),
    "decide":("decidí","decidido"), "enjoy":("disfruté","disfrutado"),
    "avoid":("evité","evitado"), "practice":("practiqué","practicado"),
    "plan":("planeé","planeado"), "accept":("acepté","aceptado"),
    "receive":("recibí","recibido"), "text":("escribí mensaje","escrito mensaje"),
    "fix":("arreglé","arreglado"), "cancel":("cancelé","cancelado"),
    "pass":("pasé","pasado"), "fail":("fallé","fallado"),
    "succeed":("tuve éxito","tenido éxito"), "manage":("gestioné","gestionado"),
    "join":("me uní","unido"), "support":("apoyé","apoyado"),
    "carry":("llevé","llevado"), "prepare":("preparé","preparado"),
    "include":("incluí","incluido"), "save":("guardé","guardado"),
    "wash":("lavé","lavado"), "review":("revisé","revisado"),
    "check":("verifiqué","verificado"), "protect":("protegí","protegido"),
    "cover":("cubrí","cubierto"), "reduce":("reduje","reducido"),
    "increase":("aumenté","aumentado"), "record":("grabé","grabado"),
    "note":("anoté","anotado"), "compare":("comparé","comparado"),
    "design":("diseñé","diseñado"), "communicate":("comuniqué","comunicado"),
    "organize":("organicé","organizado"), "describe":("describí","descrito"),
    "discuss":("discutí","discutido"), "mention":("mencioné","mencionado"),
    "notice":("noté","notado"), "suggest":("sugerí","sugerido"),
    "guess":("adiviné","adivinado"), "order":("ordené/pedí","ordenado/pedido"),
    "remind":("recordé a alguien","recordado a alguien"),
    "answer":("respondí","respondido"), "prefer":("preferí","preferido"),
    "visit":("visité","visitado"),
}

# Alternative spellings that are also correct answers (both directions).
ALT_FORMS = {
    "dreamt":("dreamed",), "dreamed":("dreamt",),
    "burnt":("burned",),   "burned":("burnt",),
    "learnt":("learned",), "learned":("learnt",),
    "smelt":("smelled",),  "smelled":("smelt",),
    "gotten":("got",),
    "canceled":("cancelled",), "cancelled":("canceled",),
    "traveled":("travelled",), "travelled":("traveled",),
    "practiced":("practised",), "practised":("practiced",),
    "realized":("realised",),   "realised":("realized",),
    "organized":("organised",), "organised":("organized",),
}

# ── Configuration constants ───────────────────────────────────────────────────
BLOCK  = 20                       # words per block when auto-splitting a list
THEMES = ("light", "dark")        # the web UI owns the actual colours (CSS vars)
VOICES = [("en-US-AriaNeural", "Aria (Female)"),
          ("en-US-GuyNeural",  "Guy (Male)")]
CATS   = {
    "regular":   {"title": "Regular verbs",   "verbs": verbos_regulares,   "has_part": False},
    "irregular": {"title": "Irregular verbs", "verbs": verbos_irregulares, "has_part": True},
}
